'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SPE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property adbrite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adbrite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrw01_012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrw01_012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrw01_01a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrw01_01a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrw01_04a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrw01_04a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrw01_04b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrw01_04b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bar_graph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bar_graph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bidvertiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bidvertiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property both_models_BC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("both_models_BC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property both_models_BC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("both_models_BC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property both_models_BC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("both_models_BC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property both_models_BC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("both_models_BC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_model_grillage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_model_grillage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashbag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashbag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exclamation_bulb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exclamation_bulb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_english01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_english01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_hebrew01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_hebrew01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property geometry_grillage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("geometry_grillage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property geometry_model() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("geometry_model", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greasypalm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greasypalm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_confirmation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_confirmation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_unknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_unknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_portal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_portal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_adina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_adina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_english() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_english", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_hebrew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_hebrew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_information01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_information01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mt_shadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mt_shadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plate_empty_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plate_empty_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property question_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quickreward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quickreward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property results_geo1_case_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("results_geo1_case_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property results_geo2_case_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("results_geo2_case_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property results_geo3_case_1and2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("results_geo3_case_1and2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property results_geo3_case_3and4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("results_geo3_case_3and4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property results_geo4_case_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("results_geo4_case_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rpoints() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rpoints", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saar_in_sunset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saar_in_sunset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SAOS_cover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAOS_cover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ship_with_stiffeners() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ship_with_stiffeners", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spe() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("spe", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SPE01_100x100() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SPE01_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SPE01_64x64() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SPE01_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SPE01_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SPE01_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
